name: Chore

on:
  pull_request:

jobs:
  models:
    name: Models
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun run models:check
